/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ControlRouteImport } from './routes/control'
import { Route as FieldRouteImport } from './routes/field'
import { Route as FreightRouteImport } from './routes/freight'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as PassengerRouteImport } from './routes/passenger'
import { Route as PrivacyRouteImport } from './routes/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightRoute = FreightRouteImport.update({
  id: '/freight',
  path: '/freight',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRoute = PassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/control': typeof ControlRoute
  '/field': typeof FieldRoute
  '/freight': typeof FreightRoute
  '/identity': typeof IdentityRoute
  '/passenger': typeof PassengerRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/control': typeof ControlRoute
  '/field': typeof FieldRoute
  '/freight': typeof FreightRoute
  '/identity': typeof IdentityRoute
  '/passenger': typeof PassengerRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/control': typeof ControlRoute
  '/field': typeof FieldRoute
  '/freight': typeof FreightRoute
  '/identity': typeof IdentityRoute
  '/passenger': typeof PassengerRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/control'
    | '/field'
    | '/freight'
    | '/identity'
    | '/passenger'
    | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/control'
    | '/field'
    | '/freight'
    | '/identity'
    | '/passenger'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/control'
    | '/field'
    | '/freight'
    | '/identity'
    | '/passenger'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ControlRoute: typeof ControlRoute
  FieldRoute: typeof FieldRoute
  FreightRoute: typeof FreightRoute
  IdentityRoute: typeof IdentityRoute
  PassengerRoute: typeof PassengerRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight': {
      id: '/freight'
      path: '/freight'
      fullPath: '/freight'
      preLoaderRoute: typeof FreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ControlRoute: ControlRoute,
  FieldRoute: FieldRoute,
  FreightRoute: FreightRoute,
  IdentityRoute: IdentityRoute,
  PassengerRoute: PassengerRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
